name: Markdownlint

on:
  push:
    paths:
      - .github/workflows/markdownlint.yml
      - .mdlrc
      - README.md

jobs:
  lint:
    name: Markdownlint
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Lint Markdown
        uses: actionshub/markdownlint@main
        with:
          path: README.md
