name: Prettier

on:
  push:
    paths:
      - .github/workflows/prettier.yml
      - README.md

jobs:
  lint:
    name: Prettier
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
        with:
          # Taken from the examples on: https://github.com/marketplace/actions/prettier-action
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Run Prettier
        uses: creyD/prettier_action@v3.3
        with:
          dry: true
          prettier_options: '**/*.md'
