name: Prettier

on:
  push:
    paths:
      - .github/workflows/prettier.yml
      - README.md

jobs:
  lint:
    name: Prettier
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Run Prettier
        uses: actionsx/prettier@v2
        with:
          args: --check '**/*.md'
